# Generated by Django 4.2.5 on 2023-09-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_fooditem_meal_mealfooditem_meal_food_items_meal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='food_items',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='meal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Backend.meal'),
        ),
        migrations.DeleteModel(
            name='MealFoodItem',
        ),
    ]
