# Generated by Django 4.2.5 on 2023-09-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_remove_meal_food_items_fooditem_meal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20),
        ),
    ]
