# Generated by Django 4.2.5 on 2023-09-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthinfo',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userhealthinfo',
            name='goal_weight_in_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userhealthinfo',
            name='height_in_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userhealthinfo',
            name='weight_in_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
