# Generated by Django 4.2.5 on 2023-09-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_userhealthinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthinfo',
            name='daily_calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
