# Generated by Django 4.2.5 on 2023-09-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_userhealthinfo_daily_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthinfo',
            name='estimated_completion_date',
            field=models.DateField(default=None),
        ),
    ]
