# Generated by Django 4.2.5 on 2023-09-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_userhealthinfo_estimated_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthinfo',
            name='daily_calories',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userhealthinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=20),
        ),
    ]
