# Generated by Django 4.2.5 on 2023-09-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_alter_userhealthinfo_daily_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthinfo',
            name='gender',
            field=models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=20),
        ),
    ]
