# Generated by Django 4.2.5 on 2023-09-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_alter_userhealthinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthinfo',
            name='daily_calories',
            field=models.IntegerField(default=0),
        ),
    ]
