# Generated by Django 4.2.5 on 2023-09-25 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_alter_userhealthinfo_daily_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthinfo',
            name='estimated_completion_date',
            field=models.DateField(default=datetime.date),
        ),
    ]
