# Generated by Django 4.2.5 on 2023-09-27 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_alter_userhealthinfo_estimated_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthinfo',
            name='estimated_completion_date',
            field=models.DateField(default=datetime.date(2023, 9, 27)),
        ),
        migrations.AlterField(
            model_name='userhealthinfo',
            name='goal_weight_in_kg',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='userhealthinfo',
            name='weight_in_kg',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
